name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # OIDC için gerekli
      contents: read   # repo’ya erişim için gerekli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::677276116587:role/GitHubActionsDeployRole
          aws-region: us-east-1   # bucket bölgen

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://tunademo.com --exclude ".git/*" --delete
