name: Deploy to S3 with IAM Role

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::677276116587:role/Tuna-GitHubActionsDeployRole"
          aws-region: "us-east-1" # bucket'ın bulunduğu region

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://your-bucket-name \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --delete
